version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.1.1
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      ELASTIC_PASSWORD: foobarbaz
    ports:
      - "9200:9200"
    networks:
      - 'elk'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    environment:
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: foobarbaz
    ports:
      - "5601:5601"
    networks:
      - 'elk'
    depends_on:
      - 'elasticsearch'

  logstash:
    image: docker.elastic.co/logstash/logstash:6.1.1
    environment:
      - 'xpack.monitoring.elasticsearch.password=foobarbaz'
    volumes:
      - /opt/elk/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - 'elk'
    depends_on:
      - 'elasticsearch'
      - 'setup_logstash'

  setup_logstash:
    image: centos:7
    volumes:
      - /opt/elk/scripts/setup-logstash.sh:/usr/local/bin/setup-logstash.sh:ro
    command: '/bin/bash -c cat /usr/local/bin/setup-logstash.sh | tr -d "\r" | bash'
    environment:
      ELASTIC_PASSWORD: foobarbaz
    networks:
      - 'elk'
    depends_on:
      - 'elasticsearch'

  setup_kibana:
    image: centos:7
    volumes:
      - /opt/elk/scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro
    command: '/bin/bash -c cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash'
    environment:
      ELASTIC_PASSWORD: foobarbaz
    networks:
      - 'elk'
    depends_on:
      - 'elasticsearch'

networks:
  elk:
    external: false
